-- # Lua language server
-- if vim.fn.executable("lua-language-server") == 1 then
--     vim.lsp.config("lua_ls", {
--         -- capabilities = capabilities,
--         cmd = { "lua-language-server" },
--         filetypes = { "lua" },
--         root_markers = { ".luarc.json", ".luarc.jsonc", ".luacheckrc", ".stylua.toml", ".git", vim.uv.cwd(), },
--         on_init = function(client)
--             if client.workspace_folders then
--                 local path = client.workspace_folders[1].name
--                 if vim.uv.fs_stat(path..'/.luarc.json') or vim.uv.fs_stat(path..'/.luarc.jsonc') then
--                     return
--                 end
--             end
--         end,
--         settings = {
--             Lua = {
--                 runtime = { version = 'LuaJIT' },
--                 hint = { enable = true },
--                 diagnostics = { globals = { "vim" } },
--
--                 -- Make the server aware of Neovim runtime files
--                 workspace = {
--                     checkThirdParty = false,
--                     library = {
--                         vim.env.VIMRUNTIME,
--                         -- Depending on the usage, you might want to add additional paths here.
--                         "${3rd}/luv/library"
--                         -- "${3rd}/busted/library",
--                     }
--                 }
--             }
--         }
--     })
--     vim.lsp.enable("lua_ls")
-- end
